---

package_dependencies:
  - "apt-transport-https"
  - "ca-certificates"
  - "cron"
  - "gnupg2"
  - "software-properties-common"

pip_dependencies:
  - "python-setuptools"
  - "python{{ '3' if ansible_python.version.major == 3 else '' }}-pip"

apt_key_id: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
apt_key_url: "https://mirrors.aliyun.com/docker-ce/linux/{{ ansible_distribution | lower }}/gpg"

apt_repository: >
  deb [arch=amd64]
  https://mirrors.aliyun.com/docker-ce/linux/{{ ansible_distribution | lower }}
  {{ ansible_distribution_release }} stable

docker_users: ["{{ ansible_env.SUDO_USER | d('root') }}"]